name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar MinGW
        run: sudo apt install mingw-w64 -y

      - name: Compilar para Windows com Makefile
        run: make CC=x86_64-w64-mingw32-gcc TARGET=rpg.exe

      - name: Publicar o exe
        uses: actions/upload-artifact@v4
        with:
          name: rpg-windows
          path: rpg.exe
